FROM docker.io/library/node:20.18-alpine AS build
RUN apk add --no-cache git
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY .babel-plugin-macrosrc.js tsconfig.json ./
COPY public ./public
COPY src ./src
ARG REACT_APP_MODE
ARG REACT_APP_ONESIGNAL_APP_ID
ARG REACT_APP_SME_ENDPOINT
ARG REACT_APP_GRAPHQL_ENDPOINT
ARG REACT_APP_GRAPHQL_WS_ENDPOINT
ARG REACT_APP_URL_FILE_UPLOAD
ARG REACT_APP_CHATTING_SOCKET_URL
ARG REACT_APP_POSTHOG_TOKEN
ARG REACT_APP_POSTHOG_HOST
ARG REACT_APP_VERSION
ENV REACT_APP_MODE=$REACT_APP_MODE
ENV REACT_APP_ONESIGNAL_APP_ID=$REACT_APP_ONESIGNAL_APP_ID
ENV REACT_APP_SME_ENDPOINT=$REACT_APP_SME_ENDPOINT
ENV REACT_APP_GRAPHQL_ENDPOINT=$REACT_APP_GRAPHQL_ENDPOINT
ENV REACT_APP_GRAPHQL_WS_ENDPOINT=$REACT_APP_GRAPHQL_WS_ENDPOINT
ENV REACT_APP_URL_FILE_UPLOAD=$REACT_APP_URL_FILE_UPLOAD
ENV REACT_APP_CHATTING_SOCKET_URL=$REACT_APP_CHATTING_SOCKET_URL
ENV REACT_APP_POSTHOG_TOKEN=$REACT_APP_POSTHOG_TOKEN
ENV REACT_APP_POSTHOG_HOST=$REACT_APP_POSTHOG_HOST
ENV REACT_APP_VERSION=$REACT_APP_VERSION
ENV NODE_ENV=production
ENV GENERATE_SOURCEMAP=false
RUN yarn run build
