import gql from "graphql-tag";

export default gql`
  query findOrderDetail($id: Int, $ref_id: String, $context: String) {
    findOrderDetail(id: $id, ref_id: $ref_id) {
      buyer_cancel_reason
      cancel_by
      sme_note
      source
      paid_at
      person_in_charge
      ship_expired_at
      payment_transaction_code
      connector_channel_code
      paid_shipping_fee
      shipping_fee_discount_from_3pl
      platform_status_text
      shipment_param_payload {
        pickup {
          address_list {
            address_id
            address_flag
            address
            city
            district
            state
            time_slot_list {
              date
              time_text
              pickup_time_id
            }
          }
        }
      }            
      total_discount
      created_at
      order_at
      currency_code
      tts_expired
      sync_error
      returnOrder {
        id
        reverse_request_time
      }
      customer {
        connector_channel_code
        created_at
        full_name
        id
        phone
        ref_id
        user_name
        updated_at
      }
      customer_id
      id
      is_old_order
      is_paid
      message_to_seller
      note
      orderItems {
        connector_channel_code
        created_at
        id
        order_id
        original_price
        paid_price
        product_name
        discount_seller_amount
        is_gift
        quantity_purchased
        reason
        reason_detail
        ref_order_id
        ref_product_id
        ref_variant_id
        variant_name
        variant_image
        variant_sku
        sc_product_id
        sc_variant_id
        package_id
        sme_id
        store_id
        updated_at
        sme_product_id
        sme_variant_id
        warehouse_error_message
        warehouse_error_code
        warehouse_step
        is_combo
        comboItems {
          id
          connector_channel_code
          order_item_id
          purchased_quantity
          sme_id
          sme_variant_id
          store_id
          warehouse_error_code
          warehouse_error_message
          warehouse_last_action
          warehouse_step
        }
      }
      original_price
      paid_price
      payment_method
      platform_status
      promotion_platform_amount
      promotion_seller_amount
      customerRecipientAddress {
        city
        connector_channel_code
        created_at
        customer_id
        district
        full_address
        full_name
        id
        phone
        district_code
        short_address
        state_code        
        region
        state
        town
        updated_at
        zip_code
      }
      logisticsPackages {
        id
        sc_warehouse_id
        sme_warehouse_id
        tracking_number
        order_id
        package_number
        create_doc_status
        shipping_carrier
        print_status
        pack_status
        pack_abnormal
        warehouse_error_message
        warehouse_step
        s3_document
        connector_channel_error
        package_weight
        package_length
        package_width
        package_height
        tracking_number
        shipping_carrier
        logisticsTrackingInfo{
          id
          tracking_update_time
          description
          package_id
          created_at
          updated_at
        }
      }
      updated_at
      update_time
      store_id
      status
      shipping_fee_by
      sme_id
      shipping_original_fee
      shipping_discount_seller_fee
      shipping_discount_platform_fee
      seller_discount_amount
      platform_discount
      ref_store_id
      ref_number
      ref_id
      recipient_address_id
      p_delivery_method
    }            
  }
`;